# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jardin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Legume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='', verbose_name='media/')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6)),
                ('disponible', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('jardin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Jardin')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(upload_to='', verbose_name='media/'),
        ),
    ]
