# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-20 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160718_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='legume',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='legume',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Prix au kilo'),
        ),
    ]
